### ISSUE TITLE
Questions on dataset generation and data leakage

### ISSUE THREAD

**Issue by HJoonKwon** [zcaicaros/L2S#1]
Thank you a lot for sharing your work and releasing the code base :)  

I have some questions on random data generation. It'd be great if you can help me understand a couple of points. 
 
You said in the paper about the data distribution, being "It is also worth noting that the training instances are generated by following distributions different from these benchmarking datasets.". How do we know that the distributions of randomly generated training data are different from those benchmarking datasets? Is there no chance of the current data generation method covering the benchmarking datasets distributions during training? Can we be sure that the data is not "leaked"? 

I thought the benchmarking dataset was the data generated from the real-world, but I guess they were also randomly generated. That triggered my questions. 

Thank you!

**Comment by zcaicaros** [comment]
Hi JoonKwon,

Thank you for being so interested in our paper.

This is a good question. If you have read the benchmark paper, you will realize that generating benchmark instances differs from uniform sampling.

For example, in the following paper:

```
E. D. Taillard. Benchmarks for basic scheduling problems.
European Journal of Operational Research, 64.2: 278-285, 1993.
doi: [10.1016/0377-2217(93)90182-M](http://dx.doi.org/10.1016/0377-2217(93)90182-M)
```

Taillard has developed a switching strategy to generate the machine permutation for each job:

![image](https://github.com/zcaicaros/L2S/assets/29399076/ef278a69-adf4-45a5-8512-c062120ef844)
![image](https://github.com/zcaicaros/L2S/assets/29399076/df9f0ec1-344f-4295-8877-7d16d0e18d91)

which is different from random permutations adopted in this paper (although in the paper we claim that we use the same strategy as Taillard's method, during implementation, by referring to our codebase, we use random permutation).

Given this observation, different benchmarks may use their own methods to generate instances. A dedicated generation process design is required, especially for hard instances, to guarantee they can find certain instances.

In addition, quoting your comments, "Is there no chance of the current data generation method covering the benchmarking datasets distributions during training? Can we be sure that the data is not "leaked"?". You refer to the concept of [support](https://web.ma.utexas.edu/users/mcudina/Lecture2_1and2_2.pdf) of different distributions. Intuitively speaking, we can have two different distributions over the same random variable, i.e., the shapes of the distribution are discrepant, while they have the same support. However, the probability of sampling certain instances will differ even if they have the same support. 

If we train our algorithm over distributions, $p$ will undoubtedly perform differently than $q$ because $q$ may give instances that are rare under $p$.

Finally, you are right that there are chances that we get instance `A` that is also covered by another distribution. However, this chance is rare for public benchmarks since they all design a sophisticated process to generate instances, and only the most difficult ones will be selected for the benchmark.

**Comment by HJoonKwon** [comment]
Thank you so much! Your answer helped me a a lot to clarify the concepts. And thanks for the great material to review. :)

**Comment by zcaicaros** [comment]
I am glad the answer helps.
